"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowDown, ArrowUpRight, BarChart3, BriefcaseBusiness, Database, Github, Linkedin, Mail, Menu, Moon, Code2, PieChart, Send, Sun, X } from "lucide-react";

const skills = {
  "Programming": ["Python", "R", "SQL"],
  "Data Stack": ["NumPy", "Pandas", "Matplotlib", "Seaborn", "Statistics"],
  "BI & Visualization": ["Power BI", "Tableau", "Excel", "Microsoft Fabric", "DAX", "Power Query"],
  "Databases": ["MySQL", "PostgreSQL", "SQL"],
  "Developer Tools": ["Git", "GitHub", "Linux", "VS Code", "Python scripting"],
  "Business Analytics": ["KPI analysis", "EDA", "Market research", "Customer insights"],
};

const projects = [
  { n:"01", title:"Sales Performance & KPI Dashboard", desc:"An executive analytics dashboard for revenue, orders, AOV, category performance and regional trends.", tags:["Power BI","SQL","Excel","DAX"], icon:BarChart3, href:"https://github.com/Riteshji108/data_analyst/tree/main/projects/sales-performance-kpi-dashboard" },
  { n:"02", title:"Customer Churn & Retention Analysis", desc:"Customer-level exploratory analysis to understand churn patterns, retention, customer concentration and revenue exposure.", tags:["Python","Pandas","NumPy","Seaborn","Power BI"], icon:PieChart, href:"https://github.com/Riteshji108/data_analyst/tree/main/projects/customer-churn-retention-analysis" },
  { n:"03", title:"Expense Tracker & Financial Analytics", desc:"A Python-based tracker with validation, structured data processing and category/monthly financial summaries.", tags:["Python","SQL","Git","File handling"], icon:Database, href:"https://github.com/Riteshji108/data_analyst/tree/main/projects/expense-tracker-financial-analytics" },
  { n:"04", title:"BFSI Transaction Intelligence", desc:"Portfolio case study for transaction-level analysis, anomaly exploration and business reporting in financial services.", tags:["Python","SQL","Power BI"], icon:BriefcaseBusiness, href:"https://github.com/Riteshji108/data_analyst" },
];

const fade = { hidden:{opacity:0,y:22}, show:{opacity:1,y:0,transition:{duration:.55}} };

export default function Home(){
  const [dark,setDark]=useState(true); const [menu,setMenu]=useState(false); const [sent,setSent]=useState(false);
  return <main className={dark?"min-h-screen bg-[#07090d] text-[#f4f7fb]":"min-h-screen bg-[#f7f9fc] text-[#10141c]"}>
    <nav className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#07090dcc] backdrop-blur-xl">
      <div className="container flex h-16 items-center justify-between"><a href="#home" className="mono text-sm font-medium"><span className="text-[#65e3b5]">RP</span> / Ritesh Pandey</a>
        <div className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a><a className="rounded-full border border-white/15 px-4 py-2" href="/resume.pdf">Resume</a><button onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div>
        <button className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>
      {menu&&<div className="container flex flex-col gap-4 border-t border-white/10 py-5 text-sm md:hidden"><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#skills" onClick={()=>setMenu(false)}>Skills</a><a href="#projects" onClick={()=>setMenu(false)}>Projects</a><a href="#experience" onClick={()=>setMenu(false)}>Experience</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></div>}
    </nav>

    <section id="home" className="grid-bg relative flex min-h-[760px] items-center overflow-hidden pt-16"><div className="glow left-[45%] top-20"/><div className="container relative grid gap-16 py-24 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
      <motion.div initial="hidden" animate="show" variants={fade}><p className="mono mb-5 text-sm text-[#65e3b5]">AVAILABLE FOR OPPORTUNITIES · DELHI, INDIA</p><h1 className="max-w-4xl text-5xl font-extrabold leading-[1.03] tracking-[-.045em] sm:text-7xl">Turning raw data into <span className="text-[#65e3b5]">clear decisions.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">I’m Ritesh Pandey, a Data Analyst and Python Developer building practical analytics solutions with Python, SQL, Excel and Power BI — while growing toward Data Engineering.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-full bg-[#65e3b5] px-5 py-3 font-semibold text-[#07100d]">View projects <ArrowDown size={17}/></a><a href="/resume.pdf" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 font-semibold">Download resume <ArrowUpRight size={17}/></a></div><div className="mt-7 flex gap-5 text-slate-400"><a href="https://github.com/Riteshji108/data_analyst" aria-label="GitHub"><Github/></a><a href="https://linkedin.com/in/ritesh-pandey-46a64528" aria-label="LinkedIn"><Linkedin/></a><a href="mailto:riteshji289@gmail.com" aria-label="Email"><Mail/></a></div></motion.div>
      <motion.div initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{duration:.7}} className="card relative overflow-hidden p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="mono text-xs text-slate-400">analytics_workspace</span><span className="h-2 w-2 rounded-full bg-[#65e3b5]"/></div><div className="grid grid-cols-2 gap-3 py-5"><Metric label="Revenue" value="₹ —"/><Metric label="Customers" value="—"/><Metric label="Growth" value="—%"/><Metric label="AOV" value="₹ —"/></div><div className="rounded-xl border border-white/10 p-4"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-semibold">Monthly performance</span><span className="mono text-xs text-slate-500">SQL → BI</span></div><div className="flex h-32 items-end gap-2">{[30,46,39,63,54,76,69,88,72,94,83,100].map((h,i)=><motion.div key={i} initial={{height:0}} animate={{height:`${h}%`}} transition={{delay:i*.04}} className="flex-1 rounded-t-sm bg-[#65e3b5]/60"/>)}</div></div><div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Code2 size={14}/> Python · SQL · Power BI · Statistics</div></motion.div>
    </div></section>

    <section id="about" className="container py-28"><Section eyebrow="01 / ABOUT" title="Analytical thinking, practical execution." text="I’m pursuing a B.Sc. at Bhaskaracharya College of Applied Sciences, University of Delhi, with a focus on building hands-on analytics projects and business-facing data solutions."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info title="Education" value="B.Sc. Polymer Science" sub="University of Delhi · 2027"/><Info title="Based in" value="New Delhi" sub="South West Delhi, India"/><Info title="Current focus" value="Data Analytics" sub="Python · SQL · BI"/><Info title="Next direction" value="Data Engineering" sub="Building toward 2027"/></div></section>

    <section id="skills" className="border-y border-white/5 bg-white/[.015] py-28"><div className="container"><Section eyebrow="02 / TOOLKIT" title="A stack built for the full analytics workflow." text="From raw data and SQL queries to dashboards and business interpretation."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Object.entries(skills).map(([group,items])=><div className="card p-6" key={group}><h3 className="mb-5 font-semibold">{group}</h3><div className="flex flex-wrap gap-2">{items.map(x=><span key={x} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300">{x}</span>)}</div></div>)}</div></div></section>

    <section id="projects" className="container py-28"><Section eyebrow="03 / SELECTED WORK" title="Projects that show how I work with data." text="Each project is designed around a business question, a reproducible workflow and a clear analytical output."/><div className="mt-12 grid gap-5 md:grid-cols-2">{projects.map((p,i)=>{const I=p.icon; return <motion.a whileHover={{y:-5}} transition={{duration:.2}} href={p.href} target="_blank" rel="noreferrer" key={p.n} className="card group block p-7"><div className="flex items-start justify-between"><span className="mono text-xs text-[#65e3b5]">{p.n}</span><I size={21} className="text-slate-500 transition group-hover:text-[#65e3b5]"/></div><h3 className="mt-12 text-xl font-bold">{p.title}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-slate-400">{p.desc}</p><div className="mt-6 flex flex-wrap gap-2">{p.tags.map(t=><span className="rounded-full bg-white/5 px-2.5 py-1 text-[11px] text-slate-300" key={t}>{t}</span>)}</div><div className="mt-7 flex items-center gap-2 text-sm font-semibold text-[#65e3b5]">View project <ArrowUpRight size={15}/></div></motion.a>})}</div></section>

    <section id="experience" className="border-y border-white/5 bg-white/[.015] py-28"><div className="container"><Section eyebrow="04 / EXPERIENCE & EDUCATION" title="Learning by building and doing."/><div className="mt-12 max-w-3xl space-y-8"><Timeline title="Power BI Intern" org="CodeAlpha" date="20 Aug 2026 — 20 Sep 2026" text="Hands-on work across Power BI, data analysis, visualization and practical analytical applications."/><Timeline title="Associate, Operations" org="Globiva · Delhi" date="Professional experience" text="Workflow coordination, stakeholder communication, service-quality execution and structured use of client/market feedback."/><Timeline title="Data Analytics Job Simulation" org="Deloitte" date="Aug 2026" text="Practical tasks across data analysis and forensic technology, strengthening structured analysis and problem-solving."/><Timeline title="B.Sc. Polymer Science" org="Bhaskaracharya College of Applied Sciences · University of Delhi" date="Expected 2027" text="Undergraduate study while developing a parallel portfolio in analytics and Python."/></div></div></section>

    <section id="contact" className="container py-28"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><Section eyebrow="05 / CONTACT" title="Let’s talk about data." text="Open to entry-level Data Analyst, Business Analyst and Python opportunities."/><div className="mt-8 space-y-3 text-sm text-slate-400"><a className="flex items-center gap-3" href="mailto:riteshji289@gmail.com"><Mail size={17}/> riteshji289@gmail.com</a><a className="flex items-center gap-3" href="https://github.com/Riteshji108/data_analyst"><Github size={17}/> GitHub</a><a className="flex items-center gap-3" href="https://linkedin.com/in/ritesh-pandey-46a64528"><Linkedin size={17}/> LinkedIn</a></div></div><form className="card p-6 sm:p-8" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="grid gap-5 sm:grid-cols-2"><Field label="Name"/><Field label="Email" type="email"/></div><label className="mt-5 block text-sm text-slate-400">Message<textarea required rows={6} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-white/[.03] p-4 text-white outline-none focus:border-[#65e3b5]"/></label><button className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#65e3b5] px-5 py-3 font-semibold text-[#07100d]" type="submit">{sent?"Message ready to send":"Send message"} <Send size={16}/></button><p className="mt-3 text-xs text-slate-500">This demo form validates locally. Connect your preferred form endpoint before production.</p></form></div></section>

    <footer className="border-t border-white/10"><div className="container flex flex-col justify-between gap-4 py-8 text-sm text-slate-500 sm:flex-row"><span>© {new Date().getFullYear()} Ritesh Pandey</span><span className="mono">DATA → INSIGHT → DECISION</span></div></footer>
  </main>
}

function Metric({label,value}:{label:string,value:string}){return <div className="rounded-xl border border-white/10 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-lg font-bold">{value}</div></div>}
function Info({title,value,sub}:{title:string,value:string,sub:string}){return <div className="card p-5"><p className="mono text-[10px] uppercase tracking-widest text-slate-500">{title}</p><p className="mt-4 font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div>}
function Section({eyebrow,title,text}:{eyebrow:string,title:string,text?:string}){return <motion.div initial="hidden" whileInView="show" viewport={{once:true,margin:"-80px"}} variants={fade}><p className="mono text-xs text-[#65e3b5]">{eyebrow}</p><h2 className="mt-4 max-w-3xl text-3xl font-bold tracking-tight sm:text-5xl">{title}</h2>{text&&<p className="mt-5 max-w-2xl leading-7 text-slate-400">{text}</p>}</motion.div>}
function Timeline({title,org,date,text}:{title:string,org:string,date:string,text:string}){return <div className="relative border-l border-white/10 pl-7"><span className="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-[#65e3b5]"/><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-[#65e3b5]">{org}</p></div><span className="mono text-[11px] text-slate-500">{date}</span></div><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></div>}
function Field({label,type="text"}:{label:string,type?:string}){return <label className="block text-sm text-slate-400">{label}<input required type={type} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] p-3.5 text-white outline-none focus:border-[#65e3b5]"/></label>}
